/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testaplikasiform;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Basil
 */
public class AddRelawan extends javax.swing.JFrame {
    Connection con;
    Statement stat;

    /**
     * Creates new form AddRelawan
     */
    public AddRelawan() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stat;
        
        //Set rata kanan kiri form //
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void Clear(){
        nama_TF.setText("");
        nohp_TF.setText("");
        alamat_TA.setText("Maks 150 huruf");
        alamat_TA.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nohp_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat_TA = new javax.swing.JTextArea();
        simpan_BTN = new javax.swing.JButton();
        clear_BTN = new javax.swing.JButton();
        home_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Input Data Relawan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No HP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        alamat_TA.setColumns(20);
        alamat_TA.setForeground(java.awt.Color.gray);
        alamat_TA.setLineWrap(true);
        alamat_TA.setRows(5);
        alamat_TA.setText("Maks 150 huruf");
        alamat_TA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alamat_TAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alamat_TAFocusLost(evt);
            }
        });
        alamat_TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alamat_TAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alamat_TAKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(alamat_TA);

        simpan_BTN.setText("Simpan");
        simpan_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_BTNActionPerformed(evt);
            }
        });

        clear_BTN.setText("Clear");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });

        home_BTN.setText("Home");
        home_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nama_TF)
                            .addComponent(nohp_TF)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(simpan_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nohp_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simpan_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_BTNActionPerformed
        // TODO add your handling code here:
        String alamat = "";
        switch (alamat_TA.getText()){
            case "Maks 150 huruf":
                alamat = "";
                break;
            default:
                alamat = alamat_TA.getText();
                break;
        }
        switch (nama_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom nama belum diisi!");
                break;
            default:
                try{
                    stat.executeUpdate("insert into tb_relawan (nama_relawan,telp_relawan,alamat_relawan) values ("
                        + "'" + nama_TF.getText()+"',"
                        + "'" + nohp_TF.getText()+"',"
                        + "'" + alamat+ "')");
                    JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
                    Clear();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
                }
                break;
        }
    }//GEN-LAST:event_simpan_BTNActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void home_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BTNActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_BTNActionPerformed

    private void alamat_TAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamat_TAFocusGained
        // TODO add your handling code here:
        if (alamat_TA.getText().equals("Maks 150 huruf")) {
            alamat_TA.setText("");
            alamat_TA.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_alamat_TAFocusGained

    private void alamat_TAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamat_TAFocusLost
        // TODO add your handling code here:
        if (alamat_TA.getText().isEmpty()) {
            alamat_TA.setForeground(Color.GRAY);
            alamat_TA.setText("Maks 150 huruf");
        }
    }//GEN-LAST:event_alamat_TAFocusLost

    private void alamat_TAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamat_TAKeyTyped
        // TODO add your handling code here:
        if(alamat_TA.getText().length()>=150) {  
            evt.consume();
        }
    }//GEN-LAST:event_alamat_TAKeyTyped

    private void alamat_TAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamat_TAKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyCode() == KeyEvent.VK_V) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            if(alamat_TA.getText().length()>=150) {  
                evt.consume();
            }
        }
    }//GEN-LAST:event_alamat_TAKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRelawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRelawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRelawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRelawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRelawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_TA;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JButton home_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_TF;
    private javax.swing.JTextField nohp_TF;
    private javax.swing.JButton simpan_BTN;
    // End of variables declaration//GEN-END:variables
}
