/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testaplikasiform;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Basil
 */
public class AddRekap extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet res;
    /**
     * Creates new form AddRekap
     */
    public AddRekap() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stat;
        tabel_donatur();
        tabel_relawan();
        
        //Set rata kanan kiri form //
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void Clear(){
        idDonatur_TF.setText("");
        namaDonatur_TF.setText("");
        tanggal_DC.setCalendar(null);
        cashTransfer_CB.setSelectedIndex(-1);
        namaBank_CB.setSelectedIndex(-1);
        namaBank_CB.setEnabled(true);
        idRelawan_TF.setText("");
        namaRelawan_TF.setText("");
        jumlahDonasi_TF.setText("");
        kegiatan_CB.setSelectedIndex(-1);
        keterangan_TA.setText("Maks 300 huruf");
        keterangan_TA.setForeground(Color.GRAY);
    }
    
    private void tabel_donatur(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Nama");
        t.addColumn("Telepon");
        donatur_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_donatur order by nama_donatur asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("nama_donatur"),
                    res.getString("telp_donatur"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void tabel_relawan(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Nama");
        t.addColumn("Telepon");
        relawan_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_relawan order by nama_relawan asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("nama_relawan"),
                    res.getString("telp_relawan"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        cashTransfer_CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simpan_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idDonatur_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jumlahDonasi_TF = new javax.swing.JTextField();
        tanggal_DC = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        donatur_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        namaDonatur_TF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan_TA = new javax.swing.JTextArea();
        namaRelawan_TF = new javax.swing.JTextField();
        idRelawan_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        relawan_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        clear_BTN = new javax.swing.JButton();
        home_BTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaBank_CB = new javax.swing.JComboBox();
        kegiatan_CB = new javax.swing.JComboBox();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cashTransfer_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Transfer" }));
        cashTransfer_CB.setSelectedIndex(-1);
        cashTransfer_CB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cashTransfer_CBItemStateChanged(evt);
            }
        });

        jLabel1.setText("Cash/Transfer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Form Rekap Donasi");

        jLabel3.setText("Tanggal Masuk");

        simpan_BTN.setText("Simpan");
        simpan_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_BTNActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama / ID Donatur");

        idDonatur_TF.setEditable(false);

        jLabel6.setText("Nama Bank");

        jLabel8.setText("Nama / ID Relawan");

        jLabel9.setText("Jumlah Donasi");

        jLabel10.setText("Kegiatan");

        jLabel11.setText("Keterangan");

        tanggal_DC.setToolTipText("");

        donatur_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donatur_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donatur_TBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(donatur_TBL);
        if (donatur_TBL.getColumnModel().getColumnCount() > 0) {
            donatur_TBL.getColumnModel().getColumn(0).setMinWidth(50);
            donatur_TBL.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        namaDonatur_TF.setEditable(false);
        namaDonatur_TF.setToolTipText("");

        keterangan_TA.setColumns(20);
        keterangan_TA.setForeground(java.awt.Color.gray);
        keterangan_TA.setLineWrap(true);
        keterangan_TA.setRows(5);
        keterangan_TA.setText("Maks 300 huruf");
        keterangan_TA.setToolTipText("");
        keterangan_TA.setName(""); // NOI18N
        keterangan_TA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keterangan_TAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keterangan_TAFocusLost(evt);
            }
        });
        keterangan_TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keterangan_TAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keterangan_TAKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(keterangan_TA);

        namaRelawan_TF.setEditable(false);

        idRelawan_TF.setEditable(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("/");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("/");

        relawan_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relawan_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relawan_TBLMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(relawan_TBL);
        if (relawan_TBL.getColumnModel().getColumnCount() > 0) {
            relawan_TBL.getColumnModel().getColumn(0).setMinWidth(50);
            relawan_TBL.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        clear_BTN.setText("Clear");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });

        home_BTN.setText("Home");
        home_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BTNActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tabel Donatur");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tabel Relawan");

        namaBank_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BCA", "BRI", "BSI", "Lainnya" }));
        namaBank_CB.setSelectedIndex(-1);
        namaBank_CB.setToolTipText("");

        kegiatan_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sedekah Jumat Berkah", "Doa Bersama Yatim", "Santunan Yatim", "Bimbel Gratis", "Sedekah Al-Quran dan Iqro", "Sedekah Air", "Qurban", "Lain-lain" }));
        kegiatan_CB.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idDonatur_TF))
                            .addComponent(cashTransfer_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggal_DC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaBank_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahDonasi_TF)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idRelawan_TF))
                            .addComponent(kegiatan_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(simpan_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tanggal_DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cashTransfer_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(namaBank_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(simpan_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahDonasi_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kegiatan_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(35, 35, 35)
                                .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_BTNActionPerformed
        // TODO add your handling code here:
        String keterangan = "";
        String namabank = "";
        String idDonatur = "";
        String idRelawan = "";
        String jumlahDonasi = "";
        String kegiatan = "";
        //String namabank = "";
        //String namabank = "";
        switch (keterangan_TA.getText()){
            case "Maks 300 huruf":
                keterangan = "";
                break;
            default:
                keterangan = keterangan_TA.getText();
                break;
        }
        switch (namaBank_CB.getSelectedIndex()){
            case -1:
                namabank = "";
                break;
            default:
                namabank = (String) namaBank_CB.getSelectedItem();
                break;
        }
        switch (idDonatur_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Nama / ID Donatur masih kosong!");
                break;
            default:
                idDonatur = idDonatur_TF.getText();
                break;
        }
        switch (idRelawan_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Nama / ID Relawan masih kosong!");
                break;
            default:
                idRelawan = idRelawan_TF.getText();
                break;
        }
        switch (jumlahDonasi_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Jumlah Donasi masih kosong!");
                break;
            default:
                jumlahDonasi = jumlahDonasi_TF.getText();
                break;
        }
        switch (kegiatan_CB.getSelectedIndex()){
            case -1:
                JOptionPane.showMessageDialog(null, "Kolom Kegiatan masih kosong!");
                break;
            default:
                kegiatan = (String) kegiatan_CB.getSelectedItem();
                break;
        }
        
        if(tanggal_DC.getDate()==null){
            JOptionPane.showMessageDialog(null, "Kalendar masih error!");
        }else{
            if(namabank==""&&namaBank_CB.isEnabled()){
                JOptionPane.showMessageDialog(null, "Nama bank masih kosong!");
            }else{
                java.sql.Date date = new java.sql.Date(tanggal_DC.getDate().getTime());
                if(idDonatur == "" || idRelawan == "" || jumlahDonasi == "" || kegiatan == "" ){
                    JOptionPane.showMessageDialog(null, "Data masih ada yang kosong!");
                }else{
                    try{
                        stat.executeUpdate("insert into tb_rekap (tgl_rekap,id_donatur,jenis_transaksi,nama_bank,id_relawan,jumlah_donasi,kegiatan,keterangan) values ("
                            + "'" + date+"',"
                            + "'" + idDonatur +"',"
                            + "'" + cashTransfer_CB.getSelectedItem() +"',"
                            + "'" + namabank +"',"
                            + "'" + idRelawan +"',"
                            + "'" + jumlahDonasi +"',"
                            + "'" + kegiatan +"',"
                            + "'" + keterangan + "')");
                        JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
                        Clear();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
                    }
                }
            }
        }
        tabel_donatur();
        tabel_relawan();
    }//GEN-LAST:event_simpan_BTNActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void home_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BTNActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_BTNActionPerformed

    private void donatur_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatur_TBLMouseClicked
        // TODO add your handling code here:
        int i = donatur_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)donatur_TBL.getValueAt(i,0);
        String code1 = (String)donatur_TBL.getValueAt(i,1);
        String code2 = "";
        try{
            res=stat.executeQuery("select * from tb_donatur where nama_donatur='"+code+"' AND telp_donatur='"+code1+"'");
            while(res.next()){
                code2 = res.getString("id_donatur");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        namaDonatur_TF.setText(code);
        idDonatur_TF.setText(code2);
    }//GEN-LAST:event_donatur_TBLMouseClicked

    private void relawan_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relawan_TBLMouseClicked
        // TODO add your handling code here:
        int i = relawan_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)relawan_TBL.getValueAt(i,0);
        String code1 = (String)relawan_TBL.getValueAt(i,1);
        String code2 = "";
        try{
            res=stat.executeQuery("select * from tb_relawan where nama_relawan='"+code+"' AND telp_relawan='"+code1+"'");
            while(res.next()){
                code2 = res.getString("id_relawan");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        namaRelawan_TF.setText(code);
        idRelawan_TF.setText(code2);
    }//GEN-LAST:event_relawan_TBLMouseClicked

    private void cashTransfer_CBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cashTransfer_CBItemStateChanged
        // TODO add your handling code here:
        if(cashTransfer_CB.getSelectedIndex()==1){
            namaBank_CB.setEnabled(true);
        } else{
            namaBank_CB.setSelectedIndex(-1);
            namaBank_CB.setEnabled(false);
            
        }
    }//GEN-LAST:event_cashTransfer_CBItemStateChanged

    private void keterangan_TAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keterangan_TAFocusGained
        // TODO add your handling code here:
        if (keterangan_TA.getText().equals("Maks 300 huruf")) {
            keterangan_TA.setText("");
            keterangan_TA.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_keterangan_TAFocusGained

    private void keterangan_TAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keterangan_TAFocusLost
        // TODO add your handling code here:
        if (keterangan_TA.getText().isEmpty()) {
            keterangan_TA.setForeground(Color.GRAY);
            keterangan_TA.setText("Maks 300 huruf");
        }
    }//GEN-LAST:event_keterangan_TAFocusLost

    private void keterangan_TAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keterangan_TAKeyTyped
        // TODO add your handling code here:
        if(keterangan_TA.getText().length()>=300) {  
            evt.consume();
        }
    }//GEN-LAST:event_keterangan_TAKeyTyped

    private void keterangan_TAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keterangan_TAKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyCode() == KeyEvent.VK_V) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            if(keterangan_TA.getText().length()>=300) {  
                evt.consume();
            }
        }
    }//GEN-LAST:event_keterangan_TAKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRekap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cashTransfer_CB;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JTable donatur_TBL;
    private javax.swing.JButton home_BTN;
    private javax.swing.JTextField idDonatur_TF;
    private javax.swing.JTextField idRelawan_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jumlahDonasi_TF;
    private javax.swing.JComboBox kegiatan_CB;
    private javax.swing.JTextArea keterangan_TA;
    private javax.swing.JComboBox namaBank_CB;
    private javax.swing.JTextField namaDonatur_TF;
    private javax.swing.JTextField namaRelawan_TF;
    private javax.swing.JTable relawan_TBL;
    private javax.swing.JButton simpan_BTN;
    private com.toedter.calendar.JDateChooser tanggal_DC;
    // End of variables declaration//GEN-END:variables
}
