/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testaplikasiform;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Basil
 */
public class EditRekap extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet res;
    /**
     * Creates new form EditRekap
     */
    public EditRekap() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stat;
        tabel_donatur();
        tabel_relawan();
        tabel_rekap();
        
        //Set rata kanan kiri form //
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void Clear(){
        idRekap_TF.setText("");
        idDonatur_TF.setText("");
        namaDonatur_TF.setText("");
        tanggal_DC.setCalendar(null);
        cashTransfer_CB.setSelectedIndex(-1);
        namaBank_CB.setSelectedIndex(-1);
        namaBank_CB.setEnabled(true);
        idRelawan_TF.setText("");
        namaRelawan_TF.setText("");
        jumlahDonasi_TF.setText("");
        kegiatan_CB.setSelectedIndex(-1);
        keterangan_TA.setText("Maks 300 huruf");
        keterangan_TA.setForeground(Color.GRAY);
    }
    
    private void tabel_donatur(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Nama");
        t.addColumn("Telepon");
        donatur_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_donatur order by nama_donatur asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("nama_donatur"),
                    res.getString("telp_donatur"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void tabel_relawan(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Nama");
        t.addColumn("Telepon");
        relawan_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_relawan order by nama_relawan asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("nama_relawan"),
                    res.getString("telp_relawan"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void tabel_rekap(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("ID");
        t.addColumn("Tanggal");
        t.addColumn("Nama Donatur");
        t.addColumn("Jenis Transaksi");
        t.addColumn("Bank");
        t.addColumn("Nama Relawan");
        t.addColumn("Jumlah Donasi");
        t.addColumn("Kegiatan");
        rekap_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_rekap inner join tb_donatur on tb_rekap.id_donatur=tb_donatur.id_donatur inner join tb_relawan on tb_rekap.id_relawan=tb_relawan.id_relawan order by tgl_rekap, id_rekap asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("id_rekap"),
                    res.getDate("tgl_rekap"),
                    res.getString("nama_donatur"),
                    res.getString("jenis_transaksi"),
                    res.getString("nama_bank"),
                    res.getString("nama_relawan"),
                    res.getString("jumlah_donasi"),
                    res.getString("kegiatan"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal_DC = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donatur_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel11 = new javax.swing.JLabel();
        namaDonatur_TF = new javax.swing.JTextField();
        jumlahDonasi_TF = new javax.swing.JTextField();
        cashTransfer_CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edit_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idDonatur_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan_TA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        delete_BTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idRekap_TF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        relawan_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jScrollPane4 = new javax.swing.JScrollPane();
        rekap_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clear_BTN = new javax.swing.JButton();
        home_BTN = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        idRelawan_TF = new javax.swing.JTextField();
        namaRelawan_TF = new javax.swing.JTextField();
        namaBank_CB = new javax.swing.JComboBox();
        kegiatan_CB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel8.setText("Nama / ID Relawan");

        jLabel9.setText("Jumlah Donasi");

        donatur_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donatur_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donatur_TBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(donatur_TBL);

        jLabel11.setText("Keterangan");

        namaDonatur_TF.setEditable(false);

        cashTransfer_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Transfer" }));
        cashTransfer_CB.setSelectedIndex(-1);
        cashTransfer_CB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cashTransfer_CBItemStateChanged(evt);
            }
        });

        jLabel1.setText("Cash/Transfer");

        jLabel3.setText("Tanggal Masuk");

        edit_BTN.setText("Edit");
        edit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_BTNActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama / ID Donatur");

        idDonatur_TF.setEditable(false);

        jLabel6.setText("Nama Bank");

        keterangan_TA.setColumns(20);
        keterangan_TA.setForeground(java.awt.Color.gray);
        keterangan_TA.setLineWrap(true);
        keterangan_TA.setRows(5);
        keterangan_TA.setText("Maks 300 huruf");
        keterangan_TA.setToolTipText("");
        keterangan_TA.setName(""); // NOI18N
        keterangan_TA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keterangan_TAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keterangan_TAFocusLost(evt);
            }
        });
        keterangan_TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keterangan_TAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keterangan_TAKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(keterangan_TA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Form Edit Rekap Donasi");

        delete_BTN.setText("Delete");
        delete_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_BTNActionPerformed(evt);
            }
        });

        jLabel7.setText("Kegiatan");

        jLabel10.setText("/");

        jLabel12.setText("ID Rekap");

        idRekap_TF.setEditable(false);

        relawan_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relawan_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relawan_TBLMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(relawan_TBL);

        rekap_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rekap_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rekap_TBLMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(rekap_TBL);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tabel Donatur");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tabel Relawan");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tabel Rekap");

        clear_BTN.setText("Clear");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });

        home_BTN.setText("Home");
        home_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BTNActionPerformed(evt);
            }
        });

        jLabel15.setText("/");

        idRelawan_TF.setEditable(false);

        namaRelawan_TF.setEditable(false);

        namaBank_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BCA", "BRI", "BSI", "Lainnya" }));
        namaBank_CB.setSelectedIndex(-1);

        kegiatan_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sedekah Jumat Berkah", "Doa Bersama Yatim", "Santunan Yatim", "Bimbel Gratis", "Sedekah Al-Quran dan Iqro", "Sedekah Air", "Qurban", "Lain-lain" }));
        kegiatan_CB.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idDonatur_TF))
                            .addComponent(tanggal_DC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashTransfer_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahDonasi_TF)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idRelawan_TF))
                            .addComponent(namaBank_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idRekap_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(kegiatan_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(idRekap_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tanggal_DC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashTransfer_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBank_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaRelawan_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jumlahDonasi_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kegiatan_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_BTNActionPerformed
        // TODO add your handling code here:
        String keterangan = "";
        String namabank = "";
        String idDonatur = "";
        String idRelawan = "";
        String jumlahDonasi = "";
        String kegiatan = "";
        switch (keterangan_TA.getText()){
            case "Maks 300 huruf":
                keterangan = "";
                break;
            default:
                keterangan = keterangan_TA.getText();
                break;
        }
        switch (namaBank_CB.getSelectedIndex()){
            case -1:
                namabank = "";
                break;
            default:
                namabank = (String) namaBank_CB.getSelectedItem();
                break;
        }
        /////
        switch (idDonatur_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Nama / ID Donatur masih kosong!");
                break;
            default:
                idDonatur = idDonatur_TF.getText();
                break;
        }
        switch (idRelawan_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Nama / ID Relawan masih kosong!");
                break;
            default:
                idRelawan = idRelawan_TF.getText();
                break;
        }
        switch (jumlahDonasi_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Jumlah Donasi masih kosong!");
                break;
            default:
                jumlahDonasi = jumlahDonasi_TF.getText();
                break;
        }
        switch (kegiatan_CB.getSelectedIndex()){
            case -1:
                JOptionPane.showMessageDialog(null, "Kolom Kegiatan masih kosong!");
                break;
            default:
                kegiatan = (String) kegiatan_CB.getSelectedItem();
                break;
        }
        if(tanggal_DC.getDate()==null){
            JOptionPane.showMessageDialog(null, "Kalendar masih kosong!");
        }else{
            java.sql.Date date = new java.sql.Date(tanggal_DC.getDate().getTime());
            if(namabank==""&&namaBank_CB.isEnabled()){
                JOptionPane.showMessageDialog(null, "Data bank kosong!");
            }else{
                if(idDonatur == "" || idRelawan == "" || jumlahDonasi == "" || kegiatan == ""){
                    JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong!");
                }else{
                    int ok=JOptionPane.showConfirmDialog(null,"Apakah anda yakin untuk edit data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
                    try{
                        String sql="update tb_rekap set tgl_rekap=?,id_donatur=?,jenis_transaksi=?,nama_bank=?,id_relawan=?,jumlah_donasi=?,kegiatan=?,keterangan=? where id_rekap='"+idRekap_TF.getText()+"'";
                        PreparedStatement st=con.prepareStatement(sql);
                        if(ok==0){
                            try{
                                st.setDate(1, date);
                                st.setString(2, idDonatur);
                                st.setString(3, (String) cashTransfer_CB.getSelectedItem());
                                st.setString(4, namabank);
                                st.setString(5, idRelawan);
                                st.setString(6, jumlahDonasi);
                                st.setString(7, kegiatan);
                                st.setString(8, keterangan);
                                st.executeUpdate();
                                JOptionPane.showMessageDialog(null,"Update Data Berhasil");
                            } catch(Exception e){
                                JOptionPane.showMessageDialog(null, "Update Data Gagal");
                            }
                        }
                    } catch (Exception e){}
                }
            }
        }
        tabel_rekap();
    }//GEN-LAST:event_edit_BTNActionPerformed

    private void delete_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_BTNActionPerformed
        // TODO add your handling code here:
        switch(idRekap_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus terlebih dahulu.");
                break;
            default:
                int ok=JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk hapus data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if(ok==0){
                    try{
                        String sql="delete from tb_rekap where id_rekap='"+idRekap_TF.getText()+"'";
                        PreparedStatement st=con.prepareStatement(sql);
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Delete Data Gagal");
                    }
                    Clear();
                }
            break;
        }
        tabel_rekap();
    }//GEN-LAST:event_delete_BTNActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void home_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BTNActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_BTNActionPerformed

    private void donatur_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatur_TBLMouseClicked
        // TODO add your handling code here:
        int i = donatur_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)donatur_TBL.getValueAt(i,0);
        String code1 = (String)donatur_TBL.getValueAt(i,1);
        String code2 = "";
        try{
            res=stat.executeQuery("select * from tb_donatur where nama_donatur='"+code+"' AND telp_donatur='"+code1+"'");
            while(res.next()){
                code2 = res.getString("id_donatur");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        namaDonatur_TF.setText(code);
        idDonatur_TF.setText(code2);
    }//GEN-LAST:event_donatur_TBLMouseClicked

    private void relawan_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relawan_TBLMouseClicked
        // TODO add your handling code here:
        int i = relawan_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)relawan_TBL.getValueAt(i,0);
        String code1 = (String)relawan_TBL.getValueAt(i,1);
        String code2 = "";
        try{
            res=stat.executeQuery("select * from tb_relawan where nama_relawan='"+code+"' AND telp_relawan='"+code1+"'");
            while(res.next()){
                code2 = res.getString("id_relawan");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        namaRelawan_TF.setText(code);
        idRelawan_TF.setText(code2);
    }//GEN-LAST:event_relawan_TBLMouseClicked

    private void rekap_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rekap_TBLMouseClicked
        // TODO add your handling code here:
        int i = rekap_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)rekap_TBL.getValueAt(i,0);
        Date code1 = (Date)rekap_TBL.getValueAt(i,1);
        String code2 = (String)rekap_TBL.getValueAt(i,2);
        String code3 = (String)rekap_TBL.getValueAt(i,3);
        String code4 = (String)rekap_TBL.getValueAt(i,4);
        String code5 = (String)rekap_TBL.getValueAt(i,5);
        String code6 = (String)rekap_TBL.getValueAt(i,6);
        String code7 = (String)rekap_TBL.getValueAt(i,7);
        String code8 = "";
        String code9 = "";
        String code10 = "";
        try{
            res=stat.executeQuery("select * from tb_rekap where id_rekap='"+code+"'");
            while(res.next()){
                code8 = res.getString("id_donatur");
                code9 = res.getString("id_relawan");
                code10 = res.getString("keterangan");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        idRekap_TF.setText(code);
        namaDonatur_TF.setText(code2);
        idDonatur_TF.setText(code8);
        tanggal_DC.setDate(code1);
        switch(code3){
            case "Cash":
                cashTransfer_CB.setSelectedIndex(0);
                break;
                
            case "Transfer":
                cashTransfer_CB.setSelectedIndex(1);
                break;
                
            default:
                break;
        }
        switch(code4){
            case "BCA":
                namaBank_CB.setSelectedIndex(0);
                break;
            case "BRI":
                namaBank_CB.setSelectedIndex(1);
                break;
            case "BSI":
                namaBank_CB.setSelectedIndex(2);
                break;
            case "Lainnya":
                namaBank_CB.setSelectedIndex(3);
                break;
            default:
                break;
        }
        
        switch(code7){
            case "Sedekah Jumat Berkah":
                kegiatan_CB.setSelectedIndex(0);
                break;
            case "Doa Bersama Yatim":
                kegiatan_CB.setSelectedIndex(1);
                break;
            case "Santunan Yatim":
                kegiatan_CB.setSelectedIndex(2);
                break;
            case "Bimbel Gratis":
                kegiatan_CB.setSelectedIndex(3);
                break;
            case "Sedekah Al-Quran dan Iqro":
                kegiatan_CB.setSelectedIndex(4);
                break;
            case "Sedekah Air":
                kegiatan_CB.setSelectedIndex(5);
                break;
            case "Qurban":
                kegiatan_CB.setSelectedIndex(6);
                break;
            case "Lain-lain":
                kegiatan_CB.setSelectedIndex(7);
                break;
            default:
                break;
        }
        namaRelawan_TF.setText(code5);
        idRelawan_TF.setText(code9);
        jumlahDonasi_TF.setText(code6);
        keterangan_TA.setText(code10);
        keterangan_TA.setForeground(Color.BLACK);
    }//GEN-LAST:event_rekap_TBLMouseClicked

    private void cashTransfer_CBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cashTransfer_CBItemStateChanged
        // TODO add your handling code here:
        if(cashTransfer_CB.getSelectedIndex()==1){
            namaBank_CB.setEnabled(true);
        } else{
            namaBank_CB.setSelectedIndex(-1);
            namaBank_CB.setEnabled(false);
        }
    }//GEN-LAST:event_cashTransfer_CBItemStateChanged

    private void keterangan_TAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keterangan_TAFocusGained
        // TODO add your handling code here:
        if (keterangan_TA.getText().equals("Maks 300 huruf")) {
            keterangan_TA.setText("");
            keterangan_TA.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_keterangan_TAFocusGained

    private void keterangan_TAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keterangan_TAFocusLost
        // TODO add your handling code here:
        if (keterangan_TA.getText().isEmpty()) {
            keterangan_TA.setForeground(Color.GRAY);
            keterangan_TA.setText("Maks 300 huruf");
        }
    }//GEN-LAST:event_keterangan_TAFocusLost

    private void keterangan_TAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keterangan_TAKeyTyped
        // TODO add your handling code here:
        if(keterangan_TA.getText().length()>=300) {  
            evt.consume();
        }
    }//GEN-LAST:event_keterangan_TAKeyTyped

    private void keterangan_TAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keterangan_TAKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyCode() == KeyEvent.VK_V) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            if(keterangan_TA.getText().length()>=300) {  
                evt.consume();
            }
        }
    }//GEN-LAST:event_keterangan_TAKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRekap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cashTransfer_CB;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JButton delete_BTN;
    private javax.swing.JTable donatur_TBL;
    private javax.swing.JButton edit_BTN;
    private javax.swing.JButton home_BTN;
    private javax.swing.JTextField idDonatur_TF;
    private javax.swing.JTextField idRekap_TF;
    private javax.swing.JTextField idRelawan_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jumlahDonasi_TF;
    private javax.swing.JComboBox kegiatan_CB;
    private javax.swing.JTextArea keterangan_TA;
    private javax.swing.JComboBox namaBank_CB;
    private javax.swing.JTextField namaDonatur_TF;
    private javax.swing.JTextField namaRelawan_TF;
    private javax.swing.JTable rekap_TBL;
    private javax.swing.JTable relawan_TBL;
    private com.toedter.calendar.JDateChooser tanggal_DC;
    // End of variables declaration//GEN-END:variables
}
