/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testaplikasiform;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Basil
 */
public class EditDonatur extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet res;

    /**
     * Creates new form EditDonatur
     */
    public EditDonatur() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stat;
        tabel_donatur();
        
        //Set rata kanan kiri form //
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void Clear(){
        idDonatur_TF.setText("");
        namaDonatur_TF.setText("");
        profesi_TF.setText("");
        nohp_TF.setText("");
        alamat_TA.setText("Maks 150 huruf");
        alamat_TA.setForeground(Color.GRAY);
    }
    
    private void tabel_donatur(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Nama");
        t.addColumn("Telepon");
        donatur_TBL.setModel(t);
        try{
            res=stat.executeQuery("select * from tb_donatur order by nama_donatur asc");
            while(res.next()){
                t.addRow(new Object[]{
                    res.getString("nama_donatur"),
                    res.getString("telp_donatur"),
                });
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaDonatur_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        profesi_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nohp_TF = new javax.swing.JTextField();
        edit_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        delete_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        donatur_TBL = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat_TA = new javax.swing.JTextArea();
        idDonatur_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clear_BTN = new javax.swing.JButton();
        home_BTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Edit Data Donatur");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama / ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No HP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Profesi");

        edit_BTN.setText("Edit");
        edit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_BTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");

        delete_BTN.setText("Delete");
        delete_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_BTNActionPerformed(evt);
            }
        });

        donatur_TBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        donatur_TBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donatur_TBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(donatur_TBL);

        alamat_TA.setColumns(20);
        alamat_TA.setForeground(java.awt.Color.gray);
        alamat_TA.setLineWrap(true);
        alamat_TA.setRows(5);
        alamat_TA.setText("Maks 150 huruf");
        alamat_TA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alamat_TAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alamat_TAFocusLost(evt);
            }
        });
        alamat_TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alamat_TAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alamat_TAKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(alamat_TA);

        idDonatur_TF.setEditable(false);

        jLabel6.setText("/");

        clear_BTN.setText("Clear");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });

        home_BTN.setText("Home");
        home_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BTNActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tabel Donatur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nohp_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(idDonatur_TF))
                                        .addComponent(profesi_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGap(104, 104, 104)
                                .addComponent(edit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDonatur_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesi_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nohp_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_BTNActionPerformed
        // TODO add your handling code here:
        String alamat = "";
        switch (alamat_TA.getText()){
            case "Maks 150 huruf":
                alamat = "";
                break;
            default:
                alamat = alamat_TA.getText();
                break;
        }
        switch (namaDonatur_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Kolom Nama / ID tidak boleh kosong!");
                break;
            default:
                int ok=JOptionPane.showConfirmDialog(null,"Apakah anda yakin untuk edit data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
                try{
                    String sql="update tb_donatur set nama_donatur=?,profesi_donatur=?,telp_donatur=?,alamat_donatur=? where id_donatur='"+idDonatur_TF.getText()+"'";
                    PreparedStatement st=con.prepareStatement(sql);
                    if(ok==0){
                        try{
                            st.setString(1,namaDonatur_TF.getText());
                            st.setString(2,profesi_TF.getText());
                            st.setString(3,nohp_TF.getText());
                            st.setString(4,alamat);
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(null,"Update Data Berhasil");
                        } catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Update Data Gagal");
                        }
                    }
                } catch (Exception e){}
                break;
        }
        tabel_donatur();
    }//GEN-LAST:event_edit_BTNActionPerformed

    private void delete_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_BTNActionPerformed
        // TODO add your handling code here:
        switch(idDonatur_TF.getText()){
            case "":
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus terlebih dahulu.");
                break;
            default:
                int ok=JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk hapus data ini?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if(ok==0){
                    try{
                        String sql="delete from tb_donatur where id_donatur='"+idDonatur_TF.getText()+"'";
                        PreparedStatement st=con.prepareStatement(sql);
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Delete Data Gagal");
                    }
                    Clear();
                }
                break;
        }
        tabel_donatur();
    }//GEN-LAST:event_delete_BTNActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void home_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BTNActionPerformed
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_BTNActionPerformed

    private void donatur_TBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donatur_TBLMouseClicked
        // TODO add your handling code here:
        int i = donatur_TBL.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)donatur_TBL.getValueAt(i,0);
        String code1 = (String)donatur_TBL.getValueAt(i,1);
        String code2 = "";
        String code3 = "";
        String code4 = "";
        try{
            res=stat.executeQuery("select * from tb_donatur where nama_donatur='"+code+"' AND telp_donatur='"+code1+"'");
            while(res.next()){
                code2 = res.getString("id_donatur");
                code3 = res.getString("profesi_donatur");
                code4 = res.getString("alamat_donatur");
                
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        namaDonatur_TF.setText(code);
        idDonatur_TF.setText(code2);
        profesi_TF.setText(code3);
        nohp_TF.setText(code1);
        alamat_TA.setText(code4);
        alamat_TA.setForeground(Color.BLACK);
    }//GEN-LAST:event_donatur_TBLMouseClicked

    private void alamat_TAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamat_TAFocusGained
        // TODO add your handling code here:
        if (alamat_TA.getText().equals("Maks 150 huruf")) {
            alamat_TA.setText("");
            alamat_TA.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_alamat_TAFocusGained

    private void alamat_TAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamat_TAFocusLost
        // TODO add your handling code here:
        if (alamat_TA.getText().isEmpty()) {
            alamat_TA.setForeground(Color.GRAY);
            alamat_TA.setText("Maks 150 huruf");
        }
    }//GEN-LAST:event_alamat_TAFocusLost

    private void alamat_TAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamat_TAKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyCode() == KeyEvent.VK_V) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            if(alamat_TA.getText().length()>=150) {  
                evt.consume();
            }
        }
    }//GEN-LAST:event_alamat_TAKeyPressed

    private void alamat_TAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamat_TAKeyTyped
        // TODO add your handling code here:
        if(alamat_TA.getText().length()>=150) {  
            evt.consume();
        }
    }//GEN-LAST:event_alamat_TAKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDonatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_TA;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JButton delete_BTN;
    private javax.swing.JTable donatur_TBL;
    private javax.swing.JButton edit_BTN;
    private javax.swing.JButton home_BTN;
    private javax.swing.JTextField idDonatur_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namaDonatur_TF;
    private javax.swing.JTextField nohp_TF;
    private javax.swing.JTextField profesi_TF;
    // End of variables declaration//GEN-END:variables
}
