/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testaplikasiform;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Basil
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        //Set rata kanan kiri form //
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relawanAdd_BTN = new javax.swing.JButton();
        relawanEdit_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        donaturAdd_BTN = new javax.swing.JButton();
        donaturEdit_BTN = new javax.swing.JButton();
        rekapAdd_BTN = new javax.swing.JButton();
        rekapEdit_BTN = new javax.swing.JButton();
        relawanView_BTN = new javax.swing.JButton();
        donaturView_BTN = new javax.swing.JButton();
        rekapView_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        relawanAdd_BTN.setText("Add");
        relawanAdd_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relawanAdd_BTNActionPerformed(evt);
            }
        });

        relawanEdit_BTN.setText("Edit/Delete");
        relawanEdit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relawanEdit_BTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Form");

        jLabel2.setText("Form Relawan");

        jLabel3.setText("Form Rekap");

        jLabel4.setText("Form Donatur");

        donaturAdd_BTN.setText("Add");
        donaturAdd_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donaturAdd_BTNActionPerformed(evt);
            }
        });

        donaturEdit_BTN.setText("Edit/Delete");
        donaturEdit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donaturEdit_BTNActionPerformed(evt);
            }
        });

        rekapAdd_BTN.setText("Add");
        rekapAdd_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapAdd_BTNActionPerformed(evt);
            }
        });

        rekapEdit_BTN.setText("Edit/Delete");
        rekapEdit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapEdit_BTNActionPerformed(evt);
            }
        });

        relawanView_BTN.setText("View Table");
        relawanView_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relawanView_BTNActionPerformed(evt);
            }
        });

        donaturView_BTN.setText("View Table");
        donaturView_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donaturView_BTNActionPerformed(evt);
            }
        });

        rekapView_BTN.setText("View Table");
        rekapView_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapView_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(relawanAdd_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(donaturAdd_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rekapAdd_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(relawanEdit_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donaturEdit_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rekapEdit_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(relawanView_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(donaturView_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rekapView_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(relawanAdd_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relawanEdit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relawanView_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(donaturAdd_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donaturEdit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donaturView_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rekapAdd_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rekapEdit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rekapView_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relawanAdd_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relawanAdd_BTNActionPerformed
        // TODO add your handling code here:
        new AddRelawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_relawanAdd_BTNActionPerformed

    private void relawanEdit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relawanEdit_BTNActionPerformed
        // TODO add your handling code here:
        new EditRelawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_relawanEdit_BTNActionPerformed

    private void donaturAdd_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donaturAdd_BTNActionPerformed
        // TODO add your handling code here:
        new AddDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_donaturAdd_BTNActionPerformed

    private void donaturEdit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donaturEdit_BTNActionPerformed
        // TODO add your handling code here:
        new EditDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_donaturEdit_BTNActionPerformed

    private void rekapAdd_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapAdd_BTNActionPerformed
        // TODO add your handling code here:
        new AddRekap().setVisible(true);
        dispose();
    }//GEN-LAST:event_rekapAdd_BTNActionPerformed

    private void rekapEdit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapEdit_BTNActionPerformed
        // TODO add your handling code here:
        new EditRekap().setVisible(true);
        dispose();
    }//GEN-LAST:event_rekapEdit_BTNActionPerformed

    private void relawanView_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relawanView_BTNActionPerformed
        // TODO add your handling code here:
        new ViewRelawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_relawanView_BTNActionPerformed

    private void donaturView_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donaturView_BTNActionPerformed
        // TODO add your handling code here:
        new ViewDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_donaturView_BTNActionPerformed

    private void rekapView_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapView_BTNActionPerformed
        // TODO add your handling code here:
        new ViewRekap().setVisible(true);
        dispose();
    }//GEN-LAST:event_rekapView_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donaturAdd_BTN;
    private javax.swing.JButton donaturEdit_BTN;
    private javax.swing.JButton donaturView_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton rekapAdd_BTN;
    private javax.swing.JButton rekapEdit_BTN;
    private javax.swing.JButton rekapView_BTN;
    private javax.swing.JButton relawanAdd_BTN;
    private javax.swing.JButton relawanEdit_BTN;
    private javax.swing.JButton relawanView_BTN;
    // End of variables declaration//GEN-END:variables
}
